name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - uses: Swatinem/rust-cache@v2
      - run: rustup update stable
      - name: Compile
        run: cargo test --features large_thread --all --verbose --no-run
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        # HACK: The cause is unknown, but on windows, the exit code is 1 even if tests are successful.
        run: cargo test --features large_thread --features pre-commit --all --verbose
      - name: Run tests (Other OS)
        if: runner.os != 'Windows'
        run: cargo test --features large_thread --all --verbose

  build-check:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - run: rustup update stable
      - run: cargo build --all --all-targets --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - run: rustup update stable
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-targets --verbose -- -D warnings
